World: world
#请注意幻潮算法与逐日算法只能同时开启一个否则将无效
#幻潮算法为以基础概率为核心的尸潮算法
#按是否发生尸潮来增加或减少次日发生尸潮的概率
#逐日算法为以随机概率为核心的尸潮算法
#按如果不发生尸潮将不断累计发生尸潮的概率
#以下为幻潮算法的配置
algo:
  #是否开启幻潮算法 与 逐日算法无法同时开启
  enable: true
  #发生尸潮的基础概率请填写1-99内的任意整数
  #1=1%,50=50%,99=99%
  baserandom: 50
  #当日发生尸潮后次日发生尸潮概率降幅
  inrandom: 10
  #当日未发生尸潮后次日发生尸潮概率增幅
  derandom: 10
  #当日发生尸潮概率=0%时次日是否重置为基础概率
  #如果关闭则之后永远不会发生尸潮
  close_0_base: false
  #当日发生尸潮概率=100%时次日是否重置为基础概率
  #如果关闭则之后永远会发生尸潮
  close_100_base: false
ttdt:
  #是否开启逐日算法 与 幻潮算法无法同时开启
  enable: true
  #是否开启逐日算法递减
  #如果关闭则次日发生尸潮的概率为前日发生尸潮概率+今日发生尸潮概率
  #即前日概率X%+今日概率Y 如果开启将按下方t_change配置项进行减幅
  t_enable: true
  #获取多少比例的前日尸潮概率
  #例如前日发生尸潮概率为50% 则减幅为50%*10%=5%
  #则今日发生尸潮概率为新的尸潮概率+5%
  t_change: 10
